### ISSUE TITLE
Duplicated note on chapter 3 main figure (+ white page)

### ISSUE THREAD

**Issue by msesboue** [KGConf/BookClub-KGsApplied#11]
The main figure of chapter 3 first introduced as Figure 3.1 page 46 contains a duplicated note. The same note is for the HPO Ontology symbol and the activity box "Ontology INgestion and Processing".

Also I have a white page on my PDF version page 63 right in between listings 3.21 and 3.22.

**Comment by giuseppefutia** [comment]
Thank you for noticing them. These issues will be fixed in the next release of the book.
