### ISSUE TITLE
Section 1.5.2 page 13 "each concept in the domain must belong to only one group", realy?

### ISSUE THREAD

**Issue by msesboue** [KGConf/BookClub-KGsApplied#6]
In Section 1.5.2 page 13 you mention "each concept in the domain must belong to only one group" speaking about taxonomy and ontology modelling. I do not believe it is true. Though it might be true for a classification (which I believe is different from a Taxonomy).

**Comment by giuseppefutia** [comment]
I agree with you, and I annotated this comment. For some cases in the biomedical domain, I noticed that the _exclusivity_ was a mandatory requirement, but this principle is not applicable in any case.
